#!/usr/bin/python3
"""  functn checking if a number is prime or not """
import sys

def m_prime(k):
    if k == 2:
        return (True)
    if k % 2 == 0:
        return (False)
    for a in range(3, int(k**0.5) + 1, 2):
        if k % a == 0:
            return (False)
    return (True)

# functn finding prime factors of a number

def fc():
    try:
        engfile = sys.argv[1]
        with open(engfile) as fd:
            for engnumber in fd:
                engnumber = int(engnumber)
                if engnumber == 2:
                    print("{}={}*{}".format(engnumber, engnumber, 1))
                    continue
                for a in range(2, int(engnumber**0.5) + 1):
                    if engnumber % a == 0 and m_prime(a):
                        q = engnumber // a
                        if m_prime(q):
                            print("{}={}*{}".format(engnumber, q, a))
                            break
                else:
                    print("{}={}*{}".format(engnumber, engnumber, 1))
    except (IndexError, FileNotFoundError):
        print("Invalid file")
