#!/usr/bin/python3
from sys import argv

with open(argv[1]) as fd:
    for line in fd:
        num = int(line)
        print("{:d}=".format(num), end='')
        if num % 2 == 0:
            print("{}*2".format(num // 2))
            continue
        for a in range(2, int(num**0.5) + 1):
            if num % a == 0:
                factor = num // a
                for b in range(2, factor, 2):
                    if factor % b == 0:
                        break
                    else:
                        print("{}*{}".format(factor, a))
                        break

