#!/usr/bin/python3
import sys

def factorize(num):
    for divisor in range(2, num + 1):
        while num % divisor == 0:
            yield divisor
            num //= divisor

def main():
    if len(sys.argv) < 2:
        print("Usage: {} <filename>".format(sys.argv[0]))
        sys.exit(1)

    filename = sys.argv[1]

    with open(filename) as file:
        for line in file:
            try:
                num = int(line.strip())
            except ValueError:
                print("Error: Invalid input '{}'".format(line.strip()))
                continue

            print("{}=".format(num), end='')

            if num % 2 == 0:
                print("{}*2".format(num // 2))
                continue

            factors = factorize(num)
            print("*".join(map(str, factors)))

if __name__ == "__main__":
    main()
